# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi_views', '0001_initial'),
        ('xiaomi_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=2000, verbose_name='评论内容')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaomi_views.PhoneDetail', verbose_name='被评论的手机')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论手机的用户')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usermoviecomment',
            unique_together=set([('user', 'phone')]),
        ),
    ]
