# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi_users', '0002_auto_20190506_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMovieComment',
            new_name='UserPhoneComment',
        ),
    ]
