# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='手机型号')),
                ('desc', models.CharField(default='暂无简介', max_length=1000, verbose_name='手机简介')),
                ('online_time', models.DateField(verbose_name='上市日期')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='手机类型')),
                ('desc', models.CharField(max_length=255, verbose_name='类型简介')),
            ],
        ),
        migrations.AddField(
            model_name='phonedetail',
            name='kind',
            field=models.ManyToManyField(to='xiaomi_views.PhoneKind'),
        ),
    ]
