# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi_views', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedetail',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
