# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi_views', '0002_phonedetail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaomi_views.PhoneDetail')),
            ],
        ),
    ]
