# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiaomi_views', '0003_phonecart'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedetail',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
